apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
# The Grafana sidecar picks up every ConfigMap with this label.
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: dashboard-sample-backend-slo
    files:
      - dashboards/sample-backend-slo.json
