apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sample-backend.name" . }}
  labels:
    {{- include "sample-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sample-backend.selector" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
