apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform
  target:
    name: grafana-admin
  dataFrom:
    - extract:
        key: prod/monitoring/grafana-admin
